site_name: My Docs
theme:
  name: material
  features:
    -navigation.tabs
    -navigation.sections
    -toc.integrate
    -navigation.top
    -search.highlight
    -content.tabs.link
    -content.code.annotation
    -content.code.copy
  language: en
  palette:
                # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
                # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to light mode